version: '3.8'

services:
  appalavra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${REACT_APP_ENVIRONMENT:-production}-appalavra
    restart: unless-stopped
    ports:
      - ${PORT:-80}:80
    environment:
      - NODE_ENV=production
    networks:
      - appalavra-network

networks:
  appalavra-network:
    driver: bridge
